Utvider hendelsene vilkar og dokumentasjonkrav sfa. LB om vilkår og dok.krav
navikt/soknadsosialhjelp-filformat pull request #143
Opened 2021-02-11 10:24 UTC by siljee

Oppdaterer hendelsene vilkar og dokumentasjonkrav sfa løsningsbeskrivelse om vilkår og dok.krav

* Legger til tittel, saksreferanse og nye statuser på vilkar
* Legger til tittel, saksreferanse, frist og nye statuser på dokumentasjonkrav
* Oppdaterer komplett.json

Se LB her: https://navno.sharepoint.com/:w:/s/TeamDigisos86/ERXKT0gR85JFugSpx6DeA1QBqpviXkNiIA_1-zOCYHtHcg?e=2JjuHU

2021-02-11 12:03 UTC, siljee commented
> Kan ikke se at du har oppdatert versjonsnummerene...

Oi! Bra catch! Lenge siden jeg har vært i filformat, så jeg glemte det helt :O

2021-02-11 12:08 UTC, siljee commented on json/digisos/soker/parts/hendelse/dokumentasjonkrav.json
> +				"ANNULLERT",
Vi har gått vekk fra `OPPFYLT` og `IKKE_OPPFYLT`. Dette fordi det krever for mye fra veiledere å holde det oppdatert. 
Men siden disse statusene benyttes av fagsystem i dag kan vi ikke fjerne de. De blir derfor "satt som `deprecated`", men det er fortsatt mulig å sende dem i innsynsfilen. I systemet vårt vil vi da anta at de er `RELEVANT`. 

Så `OPPFYLT, IKKE_OPPFYLT og RELEVANT ==> RELEVANT`

Som det står i description:
```
Status som forteller om dokumentasjonkravet er relevant eller ikke. 
RELEVANT brukes for alle dokumentasjonkrav som er relevante for saken. 
LEVERT_TIDLIGERE benyttes dersom dokumentasjonkravet er levert via andre kanaler, eller er oppfylt av et annet dokument søker har sendt inn. 
ANNULLERT benyttes dersom et dokumentasjonkrav er feilregistrert, skal fjernes av tekniske årsaker eller er erstattet av nytt vedtak. Annullerte dokumentasjonkrav vil ikke vises, og benyttes i tilfeller der et dokumentasjonkrav skal slettes fra nav.no på grunn av en feilsituasjon. 
OPPFYLT og IKKE_OPPFYLT er deprecated men fjernes ikke, for bakover-kompatibilitet. De blir tolket som RELEVANT.
```

2021-02-11 12:09 UTC, siljee commented on json/digisos/soker/parts/hendelse/dokumentasjonkrav.json
> +				"ANNULLERT",
Les gjerne kapittel 5 i løsningsbeskrivelsen: 
 https://navno.sharepoint.com/:w:/s/TeamDigisos86/ERXKT0gR85JFugSpx6DeA1QBqpviXkNiIA_1-zOCYHtHcg?e=2JjuHU 

Hvis ikke stikker jeg til utviklerprat nå :)

2021-02-23 11:19 UTC, perchrnie requested changes

2021-02-23 11:19 UTC, perchrnie commented on json/swagger.json
> +				"summary": "Versjon 1.2.0",
Jeg tror ikke dette er riktig versjonsnummer. Eller ikke det eneste som bør oppdateres.
* Linje 26ish i swagger.json
* soknad/parts/version.json (linje 7)

2021-02-23 11:20 UTC, perchrnie commented on json/swagger.json
> +				"summary": "Versjon 1.2.0",
Gammel versjon ser ut til å være 1.0.11.

2021-02-23 11:58 UTC, siljee commented on json/swagger.json
> +				"summary": "Versjon 1.2.0",
Det er sokna.json versjonen :) 
![image](https://user-images.githubusercontent.com/4296877/108840495-bb414480-75d6-11eb-9672-b8a7437cb476.png)

Mens jeg endret kun på innsynsfilen. digisos-soker.json
https://navikt.github.io/soknadsosialhjelp-filformat/#/soknad/getsoknad_json

2021-02-23 12:00 UTC, perchrnie approved these changes

2021-02-23 12:00 UTC, perchrnie commented on json/swagger.json
> +				"summary": "Versjon 1.2.0",
Aha! Jeg har opplagt ikke helt kontroll.

2021-02-23 12:39 UTC, perchrnie approved these changes

2021-02-23 16:16 UTC, merged